function value = hex2twoscomp2dec(hex)
% Converts two's complement in hex generated by 5R6-900 output reading to
% decimal percentage.

% Bit length of binary
bits = 32;

% Convert hex to bin
bin = dec2bin(hex2dec(hex));

% Convert two's complement to dec
val = bin2dec(bin);
y = sign(2^(bits - 1) - val) * (2^(bits - 1) - abs(2^(bits - 1) - val));
if ((y == 0) && (val ~= 0))
    value = -val;
else
    value = y;
end

end